<!--
    category: Zend Configuration By Yaml
    name: Route
    toolTip: Route
-->
production:
  resources:
    router:
      routes:
        home:
          type: Zend_Controller_Router_Route_Static
          route: /
          defaults:
            module: core
            controller: index
            action: index
        widget:
          type: Zend_Controller_Router_Route_Static
          route: /widget/
          defaults:
            module: widget
            controller: index
            action: index