<!--
    category: Zend Configuration By Yaml
    name: Application
    toolTip: Application
-->
production:
  phpSettings:
    display_startup_errors: true
    display_errors: true
  includePaths:
    library: APPLICATION_PATH/../library
  bootstrap:
    path: APPLICATION_PATH/Bootstrap.php
    class: Bootstrap
  appnamespace: Application
  resources:
    frontController:
      controllerDirectory: APPLICATION_PATH/controllers
      moduleDirectory: APPLICATION_PATH/modules
      defaultModule: core
      defaultControllerName: index
      defaultAction: index
      env: APPLICATION_ENV
  config:
    0: APPLICATION_PATH/configs/log.yaml
    1: APPLICATION_PATH/configs/navigation.yaml
    2: APPLICATION_PATH/configs/database.yaml
    3: APPLICATION_PATH/configs/routes.yaml
    4: APPLICATION_PATH/configs/view.yaml    

staging:
  _extends: production

testing: 
  _extends: production
  phpSettings:
    display_startup_errors: true
    display_errors: true

development:
  _extends: production
  phpSettings:
    display_startup_errors: true
    display_errors: true
  resources:
    frontController:
      params:
        displayExceptions: true
