name: {name}

web: "[http://url_to_plugin](label)"

description:

authors: "${TM_FULLNAME}"

license: "MIT License"

copyright: "&copy; ${TM_FULLNAME}"

sources:
  - "Source/Plugin.js"

author: ${TM_FULLNAME}

category: {category}

tags: [{tag}, {tag}]

current: {version}

docs: http://url_to_plugin_docs

demo: http://url_to_plugin_demo